---
- name: Vertical Scaling Playbook (Working Resize)
  hosts: localhost
  gather_facts: no

  vars:
    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "public"

  tasks:

    - name: Resize VM flavor
      openstack.cloud.compute:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          user_domain_name: "{{ os_user_domain_name }}"
          project_domain_name: "{{ os_project_domain_id }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        server: "{{ vm_name }}"
        flavor: "{{ new_flavor }}"
        action: resize
      register: resize_output

    - debug:
        msg: "Resize initiated successfully: {{ resize_output }}"

    - name: Confirm the resize
      openstack.cloud.compute:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          user_domain_name: "{{ os_user_domain_name }}"
          project_domain_name: "{{ os_project_domain_id }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        server: "{{ vm_name }}"
        action: confirm_resize
