---
- name: Vertical Scaling Playbook (Corrected)
  hosts: localhost
  gather_facts: no

  vars:
    # OpenStack AUTH (your details)
    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "public"

  tasks:

    - name: Initiate VM Resize
      openstack.cloud.server_action:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          user_domain_name: "{{ os_user_domain_name }}"
          project_domain_name: "{{ os_project_domain_id }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        server: "{{ vm_name }}"
        action: resize
        flavor: "{{ new_flavor }}"
      register: resize_result

    - debug:
        msg: "Resize initiated: {{ resize_result }}"

    - name: Confirm VM Resize
      openstack.cloud.server_action:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          user_domain_name: "{{ os_user_domain_name }}"
          project_domain_name: "{{ os_project_domain_id }}"
        region_name: "{{ os_region_name }}"
        interface: "{{ os_interface }}"
        server: "{{ vm_name }}"
        action: confirm_resize
