---
- name: Vertical Scaling via Nova API (AWX Compatible)
  hosts: localhost
  gather_facts: no

  vars:
    os_auth_url: "http://192.168.170.50:5000/v3/auth/tokens"
    os_compute_url: "http://192.168.170.50:8774/v2.1"
    os_project_name: "Production Engineering"
    os_project_domain: "Default"
    os_user_domain: "Default"
    os_username: "admin"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"

  tasks:

    - name: Authenticate to Keystone (Get Token)
      uri:
        url: "{{ os_auth_url }}"
        method: POST
        body_format: json
        return_content: yes
        status_code: 201
        body:
          auth:
            identity:
              methods: ["password"]
              password:
                user:
                  name: "{{ os_username }}"
                  domain: { name: "{{ os_user_domain }}" }
                  password: "{{ os_password }}"
            scope:
              project:
                name: "{{ os_project_name }}"
                domain: { name: "{{ os_project_domain }}" }
      register: keystone_auth

    - set_fact:
        token: "{{ keystone_auth.x_subject_token }}"

    - name: Perform Resize via Nova API
      uri:
        url: "{{ os_compute_url }}/servers/{{ vm_name }}/action"
        method: POST
        headers:
          X-Auth-Token: "{{ token }}"
        body_format: json
        status_code: 202
        body:
          resize:
            flavorRef: "{{ new_flavor }}"
      register: resize_result

    - debug:
        msg: "Resize request sent: {{ resize_result }}"

    - name: Confirm Resize
      uri:
        url: "{{ os_compute_url }}/servers/{{ vm_name }}/action"
        method: POST
        headers:
          X-Auth-Token: "{{ token }}"
        body_format: json
        status_code: 204
        body:
          confirmResize: null
      register: confirm_result

    - debug:
        msg: "Resize confirmed: {{ confirm_result }}"
