---
- name: Vertical Scaling via OpenStack CLI
  hosts: localhost
  gather_facts: no

  vars:
    os_auth_url: "http://192.168.170.50:5000/v3"
    os_project_name: "Production Engineering"
    os_project_domain: "Default"
    os_username: "admin"
    os_user_domain: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"

  tasks:

    - name: Export OpenStack environment variables
      shell: |
        export OS_AUTH_URL="{{ os_auth_url }}"
        export OS_USERNAME="{{ os_username }}"
        export OS_PASSWORD="{{ os_password }}"
        export OS_PROJECT_NAME="{{ os_project_name }}"
        export OS_USER_DOMAIN_NAME="{{ os_user_domain }}"
        export OS_PROJECT_DOMAIN_NAME="{{ os_project_domain }}"
        export OS_IDENTITY_API_VERSION=3

        openstack server resize --flavor "{{ new_flavor }}" "{{ vm_name }}"
      register: resize_out

    - debug:
        var: resize_out

    - name: Confirm the resize
      shell: |
        export OS_AUTH_URL="{{ os_auth_url }}"
        export OS_USERNAME="{{ os_username }}"
        export OS_PASSWORD="{{ os_password }}"
        export OS_PROJECT_NAME="{{ os_project_name }}"
        export OS_USER_DOMAIN_NAME="{{ os_user_domain }}"
        export OS_PROJECT_DOMAIN_NAME="{{ os_project_domain }}"
        export OS_IDENTITY_API_VERSION=3

        openstack server resize confirm "{{ vm_name }}"
      register: confirm_out

    - debug:
        var: confirm_out
