---
- name: Vertical Scaling Playbook (Legacy AWX Compatible)
  hosts: localhost
  gather_facts: no

  vars:
    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"

  tasks:

    - name: Initiate Resize on VM
      os_server_action:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          user_domain_name: "{{ os_user_domain_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
        action: resize
        server: "{{ vm_name }}"
        flavor: "{{ new_flavor }}"

    - name: Confirm Resize
      os_server_action:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
          user_domain_name: "{{ os_user_domain_name }}"
          project_domain_id: "{{ os_project_domain_id }}"
        action: confirm_resize
        server: "{{ vm_name }}"
