---
- name: Resize VM using VM NAME with Automatic Confirm
  hosts: localhost
  gather_facts: no

  vars:
    os_auth_url: "http://192.168.170.50:5000/v3/auth/tokens"
    os_compute_base: "http://192.168.170.50:8774/v2.1"
    os_project_id: "74b44d9c494348d095f0f6e92a74e229"
    os_project_name: "Production Engineering"
    os_project_domain: "default"
    os_user_domain: "Default"
    os_username: "admin"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "public"
    os_identity_api_version: 3

  tasks:

    ######################################################################
    # 1. AUTHENTICATE → GET TOKEN
    ######################################################################
    - name: Authenticate to Keystone
      uri:
        url: "{{ os_auth_url }}"
        method: POST
        body_format: json
        return_content: yes
        status_code: 201
        body:
          auth:
            identity:
              methods: ["password"]
              password:
                user:
                  name: "{{ os_username }}"
                  domain: { name: "{{ os_user_domain }}" }
                  password: "{{ os_password }}"
            scope:
              project:
                id: "{{ os_project_id }}"
      register: keystone_auth

    - set_fact:
        token: "{{ keystone_auth.x_subject_token }}"

    ######################################################################
    # 2. FIND VM UUID FROM NAME
    ######################################################################
    - name: Get server list
      uri:
        url: "{{ os_compute_base }}/servers/detail"
        method: GET
        headers:
          X-Auth-Token: "{{ token }}"
        return_content: yes
        status_code: 200
      register: server_list

    - name: Extract UUID by VM NAME
      set_fact:
        vm_id: "{{ item.id }}"
        current_status: "{{ item.status }}"
      loop: "{{ server_list.json.servers }}"
      when: item.name == vm_name

    - name: Fail if VM not found
      fail:
        msg: "VM {{ vm_name }} not found in project {{ os_project_name }}!"
      when: vm_id is not defined

    - debug:
        msg: "Found VM {{ vm_name }} → UUID: {{ vm_id }} (Status: {{ current_status }})"


    ######################################################################
    # 3. AUTO-CONFIRM PREVIOUS RESIZE IF VM IS ALREADY IN RESIZED STATE
    ######################################################################
    - name: Auto-confirm previous unfinished resize
      uri:
        url: "{{ os_compute_base }}/servers/{{ vm_id }}/action"
        method: POST
        headers:
          X-Auth-Token: "{{ token }}"
        body_format: json
        status_code: 204
        body:
          confirmResize: null
      when: current_status == "VERIFY_RESIZE" or current_status == "RESIZED"
      register: auto_confirm

    - debug:
        msg: "Auto-confirmed previous resize: {{ auto_confirm }}"
      when: current_status == "VERIFY_RESIZE" or current_status == "RESIZED"


    ######################################################################
    # 4. SEND NEW RESIZE REQUEST
    ######################################################################
    - name: Resize VM to new flavor
      uri:
        url: "{{ os_compute_base }}/servers/{{ vm_id }}/action"
        method: POST
        headers:
          X-Auth-Token: "{{ token }}"
        body_format: json
        status_code: 202
        body:
          resize:
            flavorRef: "{{ new_flavor }}"
      register: resize_output

    - debug:
        msg: "Resize initiated: {{ resize_output }}"


    ######################################################################
    # 5. WAIT FOR VERIFY_RESIZE STATE
    ######################################################################
    - name: Wait for VM to enter VERIFY_RESIZE
      uri:
        url: "{{ os_compute_base }}/servers/{{ vm_id }}"
        method: GET
        headers:
          X-Auth-Token: "{{ token }}"
        return_content: yes
        status_code: 200
      register: vm_status
      until: vm_status.json.server.status == "VERIFY_RESIZE"
      retries: 30
      delay: 5

    - debug:
        msg: "VM is now in VERIFY_RESIZE state."


    ######################################################################
    # 6. CONFIRM RESIZE AUTOMATICALLY
    ######################################################################
    - name: Confirm Resize
      uri:
        url: "{{ os_compute_base }}/servers/{{ vm_id }}/action"
        method: POST
        headers:
          X-Auth-Token: "{{ token }}"
        body_format: json
        status_code: 204
        body:
          confirmResize: null
      register: confirm_output

    - debug:
        msg: "Resize confirmed successfully: {{ confirm_output }}"
